---
title: "Final Simulation Analysis"
format:
  html:
    toc: true
    code-fold: false
execute:
  echo: true
  warning: false
  message: false
---

```{r}
library(tidyverse)
library(here)
library(broom)

experiment_folder <- here("simulation_study", "final", "data")

expt <- readRDS(file.path(experiment_folder, "experiment_table.RDS")) %>%
  filter(
    !(alpha_ij_sd > 0 & alpha_ij_mean == 0),
    !(alpha_ij_sd == 0 & alpha_ij_mean > 0)
  )

community_measures <- readRDS(file.path(experiment_folder, "community_measures.RDS")) %>%
  semi_join(expt, by = "case_id")
```

# Trait-Based Exploration

```{r}
community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = abs(20 - real_mean_b_opt),
             y = CV_totab,
             col = as_factor(b_opt_mean),
             shape = as_factor(richness))) +
  geom_point() +
  facet_wrap(alpha_ij_mean ~ alpha_ij_sd)

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = real_sd_b_opt,
             y = CV_totab,
             col = as_factor(b_opt_mean),
             shape = as_factor(richness))) +
  geom_point() +
  facet_wrap(alpha_ij_mean ~ alpha_ij_sd)

mod1 <- filter(
  community_measures,
  real_mean_b_opt > 16 & real_mean_b_opt < 24
) %>%
  lm(CV_totab ~ abs(20 - real_mean_b_opt) + real_sd_b_opt, data = .)

summary(mod1)
```

# CPC Metrics

```{r}
community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = CV_community_perf_info,
             y = CV_totab,
             col = as_factor(b_opt_mean),
             shape = as_factor(richness))) +
  geom_point() +
  facet_wrap(alpha_ij_mean ~ alpha_ij_sd)

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = CV_community_perf_naive,
             y = CV_totab,
             col = as_factor(b_opt_mean),
             shape = as_factor(richness))) +
  geom_point() +
  facet_wrap(alpha_ij_mean ~ alpha_ij_sd)

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = abs(20 - real_mean_b_opt),
             y = CV_community_perf_naive,
             col = as_factor(b_opt_mean),
             shape = as_factor(richness))) +
  geom_point()

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = real_sd_b_opt,
             y = CV_totab,
             col = abs(20 - real_mean_b_opt),
             shape = as_factor(richness))) +
  geom_point() +
  facet_grid(sd_perf_mean ~ sd_perf_range)

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = synchrony_perf_info,
             y = CV_totab,
             col = abs(20 - real_mean_b_opt),
             shape = as.factor(richness))) +
  geom_point()

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = synchrony_perf_naive,
             y = CV_totab,
             col = as.factor(sd_perf_mean),
             shape = as.factor(richness))) +
  geom_point()

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = synchrony_perf_naive,
             y = sync_ab,
             col = alpha_ij_sd),
         shape = as.factor(richness)) +
  geom_point()

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = synchrony_perf_info,
             y = sync_ab,
             col = alpha_ij_sd),
         shape = as.factor(richness)) +
  geom_point()

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = CV_totab,
             y = pop_CV_ab,
             col = alpha_ij_sd),
         shape = as.factor(richness)) +
  geom_point()

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(y = log(CV_totab),
             x = log(sync_ab),
             col = alpha_ij_sd),
         shape = as.factor(richness)) +
  geom_point()

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = avg_perf_CV_info,
             y = pop_CV_ab,
             col = alpha_ij_sd),
         shape = as.factor(richness)) +
  geom_point()

community_measures |>
  filter(real_mean_b_opt > 16 & real_mean_b_opt < 24) |>
  ggplot(aes(x = avg_perf_CV_naive,
             y = pop_CV_ab,
             col = alpha_ij_sd),
         shape = as.factor(richness)) +
  geom_point() +
  geom_smooth(method = "lm")

mod2 <- filter(
  community_measures,
  real_mean_b_opt > 16 & real_mean_b_opt < 24,
  CV_totab < 30
) %>%
  lm(CV_totab ~ CV_community_perf_naive, data = .)

mod3 <- filter(
  community_measures,
  real_mean_b_opt > 16 & real_mean_b_opt < 24
) %>%
  lm(CV_totab ~ CV_community_perf_info, data = .)

mod4 <- filter(
  community_measures,
  real_mean_b_opt > 16 & real_mean_b_opt < 24,
  alpha_ij_sd == 0
) %>%
  lm(CV_totab ~ CV_community_perf_info + real_mean_b_opt * real_sd_b_opt + richness, data = .)

mod10 <- filter(
  community_measures,
  real_mean_b_opt > 16 & real_mean_b_opt < 24
) %>%
  lm(CV_community_perf_naive ~ abs(20 - real_mean_b_opt) + real_sd_b_opt, data = .)

summary(mod2)
summary(mod3)
summary(mod4)
summary(mod10)
```
